const PRODUCTOS=[
{nombre:"Cable Delta a 2 SATA",precio:"$10.00",categoria:"Cables",imagen:"img/producto-placeholder.png",descripcion:"Duplica tu capacidad de conexión con un cable de poder Delta macho a 2 SATA hembra.",detalles:{descripcionCompleta:"Solución práctica para alimentar dos dispositivos SATA desde una conexión Delta compatible. Verifica siempre la compatibilidad del equipo antes de instalarlo.",caracteristicas:["Marca: Delta","Modelo: CA-SATA-M-HH","Color: Negro","Voltaje: 5V","Cantidad de pines: 15","Tipo de conector: SATA"],compatibilidad:"Dispositivos SATA compatibles con este tipo de alimentación.",contenido:"1 cable Delta a 2 SATA"}},
{nombre:"Cable USB 3.0",precio:"$3.00",categoria:"Cables",imagen:"img/producto-placeholder.png",descripcion:"Cable USB 3.0 para transferencia de datos y conexión de dispositivos compatibles.",detalles:{descripcionCompleta:"Cable USB 3.0 diseñado para conectar dispositivos compatibles y realizar transferencia de datos.",caracteristicas:["Conexión USB 3.0","Transferencia de datos","Diseño práctico","Conexión para dispositivos compatibles"],compatibilidad:"Computadoras y dispositivos compatibles con USB 3.0.",contenido:"1 cable USB 3.0"}}
];
const cp=document.getElementById("productos"),cc=document.getElementById("categorias"),bus=document.getElementById("buscador"),sr=document.getElementById("sinResultados");let categoriaActual="Todos";
function crearCategorias(){cc.innerHTML="";["Todos",...new Set(PRODUCTOS.map(p=>p.categoria))].forEach(c=>{let b=document.createElement("button");b.className="categoria"+(c===categoriaActual?" activa":"");b.textContent=c;b.onclick=()=>{categoriaActual=c;crearCategorias();mostrarProductos()};cc.appendChild(b)})}
function mostrarProductos(){let q=bus.value.toLowerCase().trim(),arr=PRODUCTOS.filter(p=>(categoriaActual==="Todos"||p.categoria===categoriaActual)&&(p.nombre+" "+p.descripcion+" "+p.categoria).toLowerCase().includes(q));cp.innerHTML="";sr.style.display=arr.length?"none":"block";arr.forEach(p=>{let i=PRODUCTOS.indexOf(p),card=document.createElement("article");card.className="producto";card.innerHTML=`<div class="producto-imagen"><img src="${p.imagen}" alt="${p.nombre}"></div><div class="producto-info"><div class="producto-categoria">${p.categoria}</div><h2 class="producto-nombre">${p.nombre}</h2><p class="producto-descripcion">${p.descripcion}</p><div class="producto-precio">${p.precio}</div><div class="botones-producto"><a class="producto-comprar" target="_blank" href="${wa("Hola, quiero comprar "+p.nombre+". ¿Cómo puedo realizar el pedido?")}">🛒 COMPRAR</a><button class="producto-detalles" onclick="verDetalles(${i})">ℹ DETALLES</button><a class="producto-whatsapp" target="_blank" href="${wa("Hola, estoy interesado en "+p.nombre+". ¿Me confirman disponibilidad y precio?")}">💬 CONSULTAR POR WHATSAPP</a></div></div>`;cp.appendChild(card)})}
function verDetalles(i){let p=PRODUCTOS[i];modalImagen.src=p.imagen;modalImagen.alt=p.nombre;modalCategoria.textContent=p.categoria;modalNombre.textContent=p.nombre;modalPrecio.textContent=p.precio;modalDescripcion.textContent=p.detalles.descripcionCompleta;modalCaracteristicas.innerHTML="";p.detalles.caracteristicas.forEach(x=>{let li=document.createElement("li");li.textContent=x;modalCaracteristicas.appendChild(li)});modalCompatibilidad.textContent=p.detalles.compatibilidad;modalContenido.textContent=p.detalles.contenido;modalWhatsapp.href=wa("Hola, quiero comprar "+p.nombre+". Tengo una consulta antes de realizar el pedido.");modalProducto.classList.add("activo");document.body.style.overflow="hidden"}
function cerrarDetalles(){modalProducto.classList.remove("activo");document.body.style.overflow=""}
bus.addEventListener("input",mostrarProductos);modalProducto.addEventListener("click",e=>{if(e.target===modalProducto)cerrarDetalles()});document.addEventListener("keydown",e=>{if(e.key==="Escape")cerrarDetalles()});crearCategorias();mostrarProductos();